<?php
$data = array (
  16 => 
  array (
    'cat_id' => '16',
    'cat_name' => '菜园',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 0,
    'id' => '16',
    'name' => '菜园',
  ),
  25 => 
  array (
    'cat_id' => '25',
    'cat_name' => '瓜果类',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '25',
    'name' => '瓜果类',
  ),
  23 => 
  array (
    'cat_id' => '23',
    'cat_name' => '叶菜类',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '23',
    'name' => '叶菜类',
  ),
  24 => 
  array (
    'cat_id' => '24',
    'cat_name' => '茎菜类',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '24',
    'name' => '茎菜类',
  ),
  17 => 
  array (
    'cat_id' => '17',
    'cat_name' => '果园',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 0,
    'id' => '17',
    'name' => '果园',
  ),
  26 => 
  array (
    'cat_id' => '26',
    'cat_name' => '核果类',
    'measure_unit' => '',
    'parent_id' => '17',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '26',
    'name' => '核果类',
  ),
  27 => 
  array (
    'cat_id' => '27',
    'cat_name' => '仁果类',
    'measure_unit' => '',
    'parent_id' => '17',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '27',
    'name' => '仁果类',
  ),
  21 => 
  array (
    'cat_id' => '21',
    'cat_name' => '零食铺',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '21',
    'name' => '零食铺',
  ),
  18 => 
  array (
    'cat_id' => '18',
    'cat_name' => '童年小卖部',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '18',
    'name' => '童年小卖部',
  ),
  19 => 
  array (
    'cat_id' => '19',
    'cat_name' => '米油盐',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '19',
    'name' => '米油盐',
  ),
  20 => 
  array (
    'cat_id' => '20',
    'cat_name' => '酱料坊',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '7',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '20',
    'name' => '酱料坊',
  ),
  1 => 
  array (
    'cat_id' => '1',
    'cat_name' => '手机类型',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '5',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 0,
    'id' => '1',
    'name' => '手机类型',
  ),
  4 => 
  array (
    'cat_id' => '4',
    'cat_name' => '3G手机',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '4',
    'name' => '3G手机',
  ),
  5 => 
  array (
    'cat_id' => '5',
    'cat_name' => '双模手机',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 7,
    'level' => 1,
    'id' => '5',
    'name' => '双模手机',
  ),
  2 => 
  array (
    'cat_id' => '2',
    'cat_name' => 'CDMA手机',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '2',
    'name' => 'CDMA手机',
  ),
  3 => 
  array (
    'cat_id' => '3',
    'cat_name' => 'GSM手机',
    'measure_unit' => '台',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '12',
    'level' => 1,
    'id' => '3',
    'name' => 'GSM手机',
  ),
  12 => 
  array (
    'cat_id' => '12',
    'cat_name' => '充值卡',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 0,
    'id' => '12',
    'name' => '充值卡',
  ),
  14 => 
  array (
    'cat_id' => '14',
    'cat_name' => '移动手机充值卡',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '14',
    'name' => '移动手机充值卡',
  ),
  15 => 
  array (
    'cat_id' => '15',
    'cat_name' => '联通手机充值卡',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '15',
    'name' => '联通手机充值卡',
  ),
  13 => 
  array (
    'cat_id' => '13',
    'cat_name' => '小灵通/固话充值卡',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '13',
    'name' => '小灵通/固话充值卡',
  ),
  6 => 
  array (
    'cat_id' => '6',
    'cat_name' => '手机配件',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 0,
    'id' => '6',
    'name' => '手机配件',
  ),
  11 => 
  array (
    'cat_id' => '11',
    'cat_name' => '读卡器和内存卡',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '11',
    'name' => '读卡器和内存卡',
  ),
  7 => 
  array (
    'cat_id' => '7',
    'cat_name' => '充电器',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '7',
    'name' => '充电器',
  ),
  8 => 
  array (
    'cat_id' => '8',
    'cat_name' => '耳机',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 1,
    'id' => '8',
    'name' => '耳机',
  ),
  9 => 
  array (
    'cat_id' => '9',
    'cat_name' => '电池',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '9',
    'name' => '电池',
  ),
);
?>